#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : x265
Version  : 3.3
Release  : 1
URL      : https://bitbucket.org/multicoreware/x265/downloads/x265_3.3.tar.gz
Source0  : https://bitbucket.org/multicoreware/x265/downloads/x265_3.3.tar.gz
Summary  : H.265/HEVC video encoder
Group    : Development/Tools
License  : GPL-2.0+
Requires: x265-bin = %{version}-%{release}
Requires: x265-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : nasm-bin
BuildRequires : numactl-dev

%description
=================
x265 HEVC Encoder
=================
| **Read:** | Online `documentation <http://x265.readthedocs.org/en/default/>`_ | Developer `wiki <http://bitbucket.org/multicoreware/x265/wiki/>`_
| **Download:** | `releases <http://ftp.videolan.org/pub/videolan/x265/>`_
| **Interact:** | #x265 on freenode.irc.net | `x265-devel@videolan.org <http://mailman.videolan.org/listinfo/x265-devel>`_ | `Report an issue <https://bitbucket.org/multicoreware/x265/issues?status=new&status=open>`_

%package bin
Summary: bin components for the x265 package.
Group: Binaries

%description bin
bin components for the x265 package.


%package dev
Summary: dev components for the x265 package.
Group: Development
Requires: x265-lib = %{version}-%{release}
Requires: x265-bin = %{version}-%{release}
Provides: x265-devel = %{version}-%{release}
Requires: x265 = %{version}-%{release}

%description dev
dev components for the x265 package.


%package lib
Summary: lib components for the x265 package.
Group: Libraries

%description lib
lib components for the x265 package.


%prep
%setup -q -n x265_3.3
cd %{_builddir}/x265_3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586632417
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ../source
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1586632417
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/x265

%files dev
%defattr(-,root,root,-)
/usr/include/x265.h
/usr/include/x265_config.h
/usr/lib64/libx265.so
/usr/lib64/pkgconfig/x265.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libx265.so.188
